start_urls: ['https://www.gumtree.pl/s-mieszkania-i-domy-sprzedam-i-kupie/mieszkanie/v1c9073a1dwp1?nr=10&priceType=FIXED',
             'https://www.gumtree.pl/s-mieszkania-i-domy-sprzedam-i-kupie/mieszkanie/v1c9073a1dwp1?nr=2&priceType=FIXED',
             'https://www.gumtree.pl/s-mieszkania-i-domy-do-wynajecia/mieszkanie/v1c9008a1dwp1?nr=10&priceType=FIXED',
             'https://www.gumtree.pl/s-mieszkania-i-domy-do-wynajecia/mieszkanie/v1c9008a1dwp1?nr=2&priceType=FIXED']

postgres_setup: 'postgresql://postgres:mab@localhost:5432/flats_database'